topic_header_text:
  type: string
  default: "Topic"
  description:
    en: "Topic header text."

apply_to_all:
  type: bool
  default: false
  description:
    en: "Apply above topic header text to all categories."

categories:
  type: list
  list_type: category
  default: ""
  description: 
    en: "Apply above topic header text to these categories. List category slugs in all lowercase."
